platform :ios, '8.0'
use_frameworks!

target 'SecucardConnectClientLib', :exclusive => true do
  pod "SecucardConnectClientLib", :path => "../"
  
  pod 'SwiftyJSON', '~> 2.2'
  pod 'SnapKit', '~> 0.10.0'
  pod 'Alamofire', '~> 1.2'
  #  pod 'RSBarcodes_Swift’, ’~> 0.0.5’
  
end

target 'Tests', :exclusive => true do
  pod "SecucardConnectClientLib", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end