source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.devid.net/ios-pods/ios-private-pod-repo.git'

use_frameworks!

target 'SecucardConnectSDK_Example', :exclusive => true do
  
  pod "SecucardConnectSDK", :path => "../"
  
end

target 'SecucardConnectSDK_Tests', :exclusive => true do
  
  pod "SecucardConnectSDK", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
